/** Unicode emoji + từ khóa tìm kiếm (tiếng Việt + English). */
export type EmojiEntry = {
  e: string;
  /** Chuỗi từ khóa thường, dùng để search */
  t: string;
};

export type EmojiCategory = {
  id: string;
  label: string;
  /** Icon hiển thị trên thanh danh mục */
  icon: string;
  items: EmojiEntry[];
};

export const emojiCategories: EmojiCategory[] = [
  {
    id: "smileys",
    label: "Cảm xúc",
    icon: "😀",
    items: [
      { e: "😀", t: "grin smile cười vui face" },
      { e: "😃", t: "smile eyes open happy" },
      { e: "😄", t: "smile laugh open mouth" },
      { e: "😁", t: "grin beam smile" },
      { e: "😅", t: "sweat smile nervous" },
      { e: "😂", t: "joy laugh tears haha cười" },
      { e: "🤣", t: "rofl laugh floor rolling" },
      { e: "😊", t: "blush smile shy" },
      { e: "😇", t: "angel halo innocent" },
      { e: "🙂", t: "slight smile" },
      { e: "😉", t: "wink nháy mắt" },
      { e: "😍", t: "heart eyes love love eyes" },
      { e: "🥰", t: "smile hearts love" },
      { e: "😘", t: "kiss flying heart" },
      { e: "😗", t: "kiss whistle" },
      { e: "😙", t: "kiss smile eyes" },
      { e: "😚", t: "kiss closed eyes" },
      { e: "😋", t: "yum delicious tongue" },
      { e: "😛", t: "tongue out silly tongue" },
      { e: "😜", t: "wink tongue crazy" },
      { e: "🤪", t: "zany crazy" },
      { e: "😝", t: "squint tongue" },
      { e: "🤑", t: "money mouth rich" },
      { e: "🤗", t: "hugs hugging" },
      { e: "🤭", t: "hand over mouth oops" },
      { e: "🤫", t: "shush quiet" },
      { e: "🤔", t: "thinking think suy nghĩ" },
      { e: "🤐", t: "zipper mouth silent" },
      { e: "🤨", t: "raised eyebrow suspicious" },
      { e: "😐", t: "neutral meh" },
      { e: "😑", t: "expressionless blank" },
      { e: "😶", t: "no mouth speechless" },
      { e: "😏", t: "smirk smug" },
      { e: "😣", t: "persevere struggle" },
      { e: "😥", t: "sad relieved tear" },
      { e: "😮", t: "open mouth surprise wow" },
      { e: "😯", t: "hushed surprise" },
      { e: "😪", t: "sleepy tired" },
      { e: "😫", t: "tired exhausted" },
      { e: "😴", t: "sleeping sleep ngủ zzz" },
      { e: "😌", t: "relieved peaceful" },
      { e: "🤤", t: "drooling hungry" },
      { e: "😒", t: "unamused annoyed" },
      { e: "😓", t: "sweat cold" },
      { e: "😔", t: "pensive sad" },
      { e: "😕", t: "confused" },
      { e: "🙃", t: "upside down" },
      { e: "🤢", t: "nauseated sick" },
      { e: "🤮", t: "vomit sick" },
      { e: "🤧", t: "sneeze cold" },
      { e: "😷", t: "mask face medical" },
      { e: "🤒", t: "thermometer sick fever" },
      { e: "🤕", t: "bandage hurt" },
      { e: "🥳", t: "party partying celebration" },
      { e: "😎", t: "cool sunglasses" },
      { e: "🤓", t: "nerd glasses" },
      { e: "😭", t: "cry sob tears khóc" },
      { e: "😢", t: "tear sad" },
      { e: "😤", t: "triumph steam angry" },
      { e: "😠", t: "angry mad giận" },
      { e: "😡", t: "pouting rage red face" },
      { e: "🤬", t: "cursing symbols" },
      { e: "🤯", t: "exploding head mind blown" },
      { e: "😳", t: "flushed embarrassed" },
      { e: "🥰", t: "love hearts" },
      { e: "🥺", t: "pleading puppy eyes" },
      { e: "🤩", t: "star star eyes" },
      { e: "🥱", t: "yawn yawning sleepy" },
    ],
  },
  {
    id: "gestures",
    label: "Cử chỉ",
    icon: "👋",
    items: [
      { e: "👋", t: "wave hand vẫy chào" },
      { e: "🤚", t: "raised back of hand" },
      { e: "🖐️", t: "hand fingers splayed" },
      { e: "✋", t: "raised hand stop" },
      { e: "🖖", t: "vulcan salute spock" },
      { e: "👌", t: "ok hand perfect" },
      { e: "🤌", t: "pinched fingers italian" },
      { e: "🤏", t: "pinching small" },
      { e: "✌️", t: "peace victory v" },
      { e: "🤞", t: "fingers crossed luck" },
      { e: "🤟", t: "love you gesture" },
      { e: "🤘", t: "rock horns rock" },
      { e: "🤙", t: "call me shaka" },
      { e: "👈", t: "point left" },
      { e: "👉", t: "point right" },
      { e: "👆", t: "point up" },
      { e: "👇", t: "point down" },
      { e: "☝️", t: "point up index" },
      { e: "👍", t: "thumbs up like ok tốt" },
      { e: "👎", t: "thumbs down dislike" },
      { e: "✊", t: "fist raised punch" },
      { e: "👊", t: "oncoming fist bump" },
      { e: "🤛", t: "left fist" },
      { e: "🤜", t: "right fist" },
      { e: "👏", t: "clap applause vỗ tay" },
      { e: "🙌", t: "raised hands celebrate" },
      { e: "👐", t: "open hands open" },
      { e: "🤲", t: "palms up together" },
      { e: "🤝", t: "handshake deal" },
      { e: "🙏", t: "pray thanks pray thanks cảm ơn" },
      { e: "😶‍🌫️", t: "face in clouds" },
      { e: "💪", t: "flex muscle strong bắp tay" },
      { e: "🦵", t: "leg" },
      { e: "🦶", t: "foot" },
      { e: "👂", t: "ear" },
      { e: "👃", t: "nose" },
    ],
  },
  {
    id: "animals",
    label: "Động vật",
    icon: "🐱",
    items: [
      { e: "🐶", t: "dog chó puppy" },
      { e: "🐱", t: "cat mèo kitten" },
      { e: "🐭", t: "mouse" },
      { e: "🐹", t: "hamster" },
      { e: "🐰", t: "rabbit thỏ" },
      { e: "🦊", t: "fox" },
      { e: "🐻", t: "bear gấu" },
      { e: "🐼", t: "panda" },
      { e: "🐨", t: "koala" },
      { e: "🐯", t: "tiger hổ" },
      { e: "🦁", t: "lion sư tử" },
      { e: "🐮", t: "cow bò" },
      { e: "🐷", t: "pig heo" },
      { e: "🐸", t: "frog ếch" },
      { e: "🐵", t: "monkey khỉ" },
      { e: "🐔", t: "chicken gà" },
      { e: "🐧", t: "penguin chim cánh cụt" },
      { e: "🐦", t: "bird chim" },
      { e: "🐤", t: "baby chick" },
      { e: "🦆", t: "duck vịt" },
      { e: "🦅", t: "eagle đại bàng" },
      { e: "🦉", t: "owl cú" },
      { e: "🤠", t: "cowboy hat" },
      { e: "🤡", t: "clown" },
    ],
  },
  {
    id: "food",
    label: "Đồ ăn",
    icon: "🍕",
    items: [
      { e: "🍎", t: "apple táo red fruit" },
      { e: "🍊", t: "orange quýt" },
      { e: "🍋", t: "lemon chanh" },
      { e: "🍌", t: "banana chuối" },
      { e: "🍉", t: "watermelon dưa hấu" },
      { e: "🍇", t: "grapes nho" },
      { e: "🍓", t: "strawberry dâu" },
      { e: "🐟", t: "fish cá sushi" },
      { e: "🍕", t: "pizza pizza" },
      { e: "🍔", t: "burger hamburger" },
      { e: "🍟", t: "fries french fries khoai" },
      { e: "🌭", t: "hot dog xúc xích" },
      { e: "🍿", t: "popcorn bắp rang" },
      { e: "🧂", t: "salt muối" },
      { e: "🥚", t: "egg trứng" },
      { e: "🍳", t: "cooking egg pan" },
      { e: "🍱", t: "bento box cơm hộp" },
      { e: "🍜", t: "ramen noodle mì phở" },
      { e: "🍲", t: "stew pot soup" },
      { e: "🍣", t: "sushi sushi" },
      { e: "🍤", t: "fried shrimp tempura" },
      { e: "🍩", t: "donut bánh ngọt" },
      { e: "🍰", t: "cake bánh kem" },
      { e: "🎂", t: "birthday cake sinh nhật" },
      { e: "🍺", t: "beer beer bia" },
      { e: "🍻", t: "cheers clink beers" },
      { e: "🥂", t: "clinking glasses champagne" },
      { e: "🍷", t: "wine wine rượu" },
      { e: "☕", t: "coffee coffee cà phê" },
      { e: "🍵", t: "tea trà matcha" },
      { e: "🤤", t: "drool yum food" },
    ],
  },
  {
    id: "travel",
    label: "Du lịch",
    icon: "✈️",
    items: [
      { e: "🚗", t: "car car ô tô xe" },
      { e: "🚕", t: "taxi taxi" },
      { e: "🚌", t: "bus bus xe buýt" },
      { e: "🚲", t: "bike bicycle xe đạp" },
      { e: "✈️", t: "airplane plane máy bay" },
      { e: "🚀", t: "rocket tên lửa" },
      { e: "🛸", t: "ufo flying saucer" },
      { e: "🚁", t: "helicopter trực thăng" },
      { e: "⛵", t: "sailboat thuyền" },
      { e: "🗺️", t: "map bản đồ" },
      { e: "🧭", t: "compass la bàn" },
      { e: "🏠", t: "house home nhà" },
      { e: "🏢", t: "office building văn phòng" },
      { e: "🏖️", t: "beach beach biển" },
      { e: "🌋", t: "volcano núi lửa" },
      { e: "🏔️", t: "mountain snow núi" },
      { e: "🌅", t: "sunrise bình minh" },
      { e: "🌄", t: "sunrise mountains" },
      { e: "🌈", t: "rainbow cầu vồng" },
      { e: "🎡", t: "ferris wheel" },
      { e: "🎢", t: "roller coaster" },
    ],
  },
  {
    id: "activities",
    label: "Hoạt động",
    icon: "⚽",
    items: [
      { e: "⚽", t: "soccer football bóng đá" },
      { e: "🏀", t: "basketball bóng rổ" },
      { e: "🎾", t: "tennis quần vợt" },
      { e: "🏐", t: "volleyball bóng chuyền" },
      { e: "🎮", t: "video game game console" },
      { e: "🎯", t: "dart target" },
      { e: "🎲", t: "dice dice xúc xắc" },
      { e: "🎸", t: "guitar guitar guitar" },
      { e: "🎤", t: "microphone microphone mic" },
      { e: "🎧", t: "headphone headphone tai nghe" },
      { e: "🎬", t: "clapper movie film" },
      { e: "🎨", t: "palette art paint" },
      { e: "🎭", t: "theater masks drama" },
      { e: "🎪", t: "circus tent" },
    ],
  },
  {
    id: "objects",
    label: "Đồ vật",
    icon: "💡",
    items: [
      { e: "⌚", t: "watch đồng hồ" },
      { e: "📱", t: "phone mobile iphone điện thoại" },
      { e: "💻", t: "laptop laptop máy tính" },
      { e: "⌨️", t: "keyboard bàn phím" },
      { e: "🖱️", t: "mouse chuột" },
      { e: "💡", t: "light bulb idea đèn" },
      { e: "🔦", t: "flashlight đèn pin" },
      { e: "📷", t: "camera camera" },
      { e: "📚", t: "books books sách" },
      { e: "📖", t: "open book đọc" },
      { e: "✏️", t: "pencil bút chì" },
      { e: "📝", t: "memo note ghi chú" },
      { e: "🎁", t: "gift quà tặng" },
      { e: "🔑", t: "key chìa khóa" },
      { e: "🛎️", t: "bell bell chuông" },
      { e: "⏰", t: "alarm clock báo thức" },
      { e: "💰", t: "money bag tiền" },
      { e: "💳", t: "credit card thẻ" },
      { e: "📧", t: "email mail thư" },
      { e: "📎", t: "paperclip kẹp giấy" },
    ],
  },
  {
    id: "symbols",
    label: "Ký hiệu",
    icon: "❤️",
    items: [
      { e: "❤️", t: "heart red love tim yêu" },
      { e: "🧡", t: "orange heart" },
      { e: "💛", t: "yellow heart" },
      { e: "💚", t: "green heart" },
      { e: "💙", t: "blue heart" },
      { e: "💜", t: "purple heart" },
      { e: "🖤", t: "black heart" },
      { e: "💔", t: "broken heart heartbreak" },
      { e: "❣️", t: "heart exclamation" },
      { e: "💯", t: "100 hundred perfect" },
      { e: "⭐", t: "star star sao" },
      { e: "🌟", t: "glowing star sparkle" },
      { e: "✨", t: "sparkles sparkle lấp lánh" },
      { e: "⚡", t: "lightning zap điện" },
      { e: "🔥", t: "fire fire flame lửa hot" },
      { e: "💧", t: "droplet water nước" },
      { e: "✅", t: "check mark done tick xong" },
      { e: "❌", t: "cross mark no wrong sai" },
      { e: "❓", t: "question mark question hỏi" },
      { e: "❗", t: "exclamation mark cảnh báo" },
      { e: "🆗", t: "ok ok button" },
      { e: "🆒", t: "cool cool" },
      { e: "🆕", t: "new new" },
      { e: "🆓", t: "free free" },
      { e: "🔔", t: "bell notification thông báo" },
      { e: "🔕", t: "bell slash mute im lặng" },
      { e: "🔒", t: "lock locked khóa" },
      { e: "🔓", t: "unlock mở khóa" },
    ],
  },
];

/** Flatten all emojis for search across categories. */
export function getAllEmojiEntries(): EmojiEntry[] {
  return emojiCategories.flatMap((c) => c.items);
}

export function searchEmojis(query: string): EmojiEntry[] {
  const q = query.trim().toLowerCase();
  const all = getAllEmojiEntries();
  if (!q) return [];
  const seen = new Set<string>();
  const out: EmojiEntry[] = [];
  for (const item of all) {
    if (seen.has(item.e)) continue;
    if (item.t.includes(q) || item.e.includes(q)) {
      seen.add(item.e);
      out.push(item);
    }
  }
  return out;
}
